---
title: "Python basics"
format: html
---


## Setup

Everything needs to be installed before getting to this stage.
The examples are using a conda env.

### pandas

```{python}
import numpy as np
import pandas as pd
```

### Polars

```{python}
import polars as pl
```

### DuckDB
```{python}
import duckdb
```

### Arrow

```{python}
import pyarrow as pa
```

## Creating

### pandas

It may be easiest to start from a dictionary.

```{python}
# create the column dictionary
input_dict = {
    'languages': ['Fortran', 'R', 'Python', 'Julia'],
    'created': [1957, 1993, 1991, 2012],
    'has_syllabus': [False, True, True, True]
    }
input_dict
```

Convert to DataFrame, with keys becoming the column headers:

```{python}
df = pd.DataFrame(input_dict)
df
```

The default display does not show types, so get these in an extra step.

```{python}
df.dtypes
```

### Polars

```{python}
# create the column dictionary
input_dict = {
    'languages': ['Fortran', 'R', 'Python', 'Julia'],
    'created': [1957, 1993, 1991, 2012],
    'has_syllabus': [False, True, True, True]
    }
input_dict
```

Convert to DataFrame, with keys becoming the column headers:

```{python}
pl_df = pl.DataFrame(input_dict)
pl_df
```

Note that the default display is not really Pythonic, with double-quoted string and lowercase bools.
We are working with a thin layer over Rust.

### DuckDB

Creating a data source from scratch within DuckDB is relatively unusual.

Just use whatever you have: pandas or Polars dataframes, CSV, Parquet or JSON files, remote database connections...

### Arrow

TODO


## Importing data

### pandas

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO


## Subsetting

An important difference is whether row names are used (pandas) or not (Polars, SQL).

### pandas

In our toy example, we set column names:

```{python}
df.columns
```

Row "names" are called the `index` in pandas.
We did not set them explicitly, so pandas falls back to the implicit index of sequential integers.

The explicit/implicit distinction is important in pandas indexing, and in Python "explicit is better than implcit".

```{python}
df.index
```

To get a cell value, the `.at` attribute uses explicit indices, `.iat` uses implicit.
The `[row, col]` syntax copies Numpy.

```{python}
df.at[2, 'languages']
```

```{python}
df.iat[1, 0]
```

Retrieve a single column with indexing, or use the column name as an attribute.

```{python}
df['languages']
```

```{python}
df.languages
```

For multiple columns, use `.loc` or `.iloc` with a list or a range of columns.
As in NumPy, the `:, ` means all rows:

```{python}
df.loc[:, 'languages':'created']
```

Note that pandas ranges differ from core Python, as both the start and the stop are _included_.

For regex matching of column names, use the `filter()` method (which can also do other things).

```{python}
df.filter(regex = '^[lh]')
```


### Polars

TODO

### DuckDB

TODO

### Arrow

TODO


## Sorting

### pandas

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO


## Modifying

### pandas

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO

