---
title: "R basics"
format: 
  html:
    code-fold: false
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    geometry:
      - top=15mm
      - bottom=20mm
      - heightrounded
---


## Setup

Other than `data.frame`, packages need to be installed before getting to this stage.

### data.frame

No setup needed: this is part of Base R.

### tibble

Either `library(tibble)` or (preferably) `library(tidyverse)`.
The latter also brings in important libraries such as `dplyr`.

```{R}
library(tidyverse)
```

Documentation is fairly extensive, in the Tidyverse style:

- A [website][web-tibble].
- A [function reference][ref-tibbles].
- A [chapter][book-tibble] in R for Data Science.

### data.table

Caution: this does not always play nicely with `tidyverse`.
It is designed as an alternative approach, not a complement.

```{R}
library(data.table)
```

The first time  the library is attached, it gives configuration information.
On my system:

```
data.table 1.18.4 using 8 threads (see ?getDTthreads).  Latest news: r-datatable.com
```

### Polars

The R bindings for Polars are available in `r-multiverse`, but not in CRAN.

### DuckDB

```{R}
library("duckdb")
```

### Arrow

TODO

### PostgreSQL

TODO

## Creating

### data.frame

```{R}
# create the column vectors
languages <- c("Fortran", "R", "Python", "Julia")
created <- c(1957, 1993, 1991, 2012)
has.syllabus <- c(FALSE, TRUE, TRUE, TRUE)

# join columns to create the dataframe
df <- data.frame(languages, created, has.syllabus)
df
```

```{R}
# look at the structure
str(df)
```

### tibble

```{R}
# column vectors are same as for data.frame
tbl <- tibble(languages, created, has.syllabus)
tbl
```

```{R}
str(tbl)
```

### data.table

### Polars

### DuckDB

### Arrow


## Importing data

### data.frame

### tibble

### data.table

### Polars

### DuckDB

### Arrow

## Subsetting

### data.frame & tibble

Dataframes, including tibbles, can be treated as lists of column vectors, so list indexing recovers a specified column.

```{R}
tbl
```

```{R}
tbl$created
```

A dataframe can also be indexed with [matrix-style][concept-matrices-arrays] indexing.

```{R}
tbl[c(2, 4), 1:2]
```

Using `dplyr`, get a single column with [`pull()`][ref-pull] with the name or sequential number (negative numbers to count right-to-left).

```{R}
tbl |> pull(created)
```

This is the same result as `tbl$created`, but using a pipeline-friendly function.

To get multiple columns, the appropriate function is [`select()`][ref-select], which is highly versatile.
Get (or drop) columns based on properties of their name or type.

```{R}
# Range with position and/or name
tbl |> select(1:created)
```

```{R}
# Exclude a column
tbl |> select(!created)
```

```{R}
# Use type of column
tbl |> select(where(is.numeric))
```

Multiple criteria are allowed, using Boolean operators `&`, `|` and `!` (and, or not).

Column names that are _valid R identifiers_ do not need quotes within a [`select()`][ref-select].
Invalid names (e.g. those including spaces) can be enclosed in backticks, though renaming them might be better.

The [`select()`][ref-select] function can work with a range of helper functions to pick column names: [`starts_with`][ref-starts_with], [`contains`][ref-starts_with], [`num_range`][ref-starts_with] and various others.
[`matches`][ref-starts_with] allows full [RegEx][concept-regex] matching.
See the [documentation][ref-select] for details.

```{R}
# limit display to top 3 rows of non-list columns
starwars |> 
  select(!where(is.list)) |> 
  head(3)
```

```{R}
# pick a subset of columns
starwars |> 
  select(name | ends_with("color")) |> 
  head(5)
```

Get rows matching some criteria with [`filter()`][ref-filter], or exclude them with `filter_out()`.

```{R}
starwars |> 
  select(name:mass) |> 
  filter(between(height, 150, 165) & !is.na(mass))
```

Filter criteria can be arbitrarily complex, but always based on row _contents_.

If row _numbers_ are known, we can use a variety of [`slice()`][ref-slice] functions.

```{R}
starwars |> 
  select(name | homeworld) |> 
  slice(20:25)
```

```{R}
# random sample of rows
starwars |> 
  select(name | homeworld) |> 
  slice_sample(n = 4)
```

To remove duplicate rows, use [`distinct()`][ref-distinct].

### data.table

TODO

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO

## Sorting

### data.frame & tibble

[`arrange()`][ref-arrange] sorts rows by the values in one or more columns.

```{R}
tbl
```

```{R}
tbl |> arrange(languages)
```

### data.table

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO


## Modifying

### data.frame & tibble

Column names can be changed with [`rename(newname = oldname)`][ref-rename], or `rename_with()` to apply a function.
A typical use would be cleaning up imported names to make them easier to work with in R, by removing whitespace and forcing a consistent format for related names.

Note the syntax within `rename()`.
The _contents_ of column `oldname` are _bound_ to name `newname`, hence the order.

Column order can be changed with [`relocate()`][ref-relocate].
Specified column(s) are moved to the left-most position(s) by default, but a `.before` or `.after` argument can be used for finer positioning.

```{R}
sw <- starwars |> select(name:species) |> slice(1:4)
sw
```

```{R}
sw |> relocate(c(species, homeworld), .after = name)
```

For bigger changes, [`mutate()`][ref-mutate] lets you:

- Create new columns that are functions of existing columns.
- Replace an existing column, by creating a new column with the same name.
- Delete a column, by setting its value to [`NULL`][concept-nothingness]

```{R}
starwars |> 
  select(c(name, species, height, mass)) |> 
  mutate(BMI = mass / (height / 100)^2) |> 
  head(4)
```

When you want to operate on a subset of the columns with functions such as `mutate()`, the `select() |> mutate()` sequence in the above example is one option.
Only the selected columns will be in the result.

Alternatively, it can be convenient to use [`pick()`][ref-pick] _within_ the `mutate()` call:

```{R}
starwars |> mutate(pick(c(name, species, height, mass)), BMI = mass / (height / 100)^2) |> head(4)
```

When you want to operate on a subset of the columns with functions such as `mutate()`, the `select() |> mutate()` sequence in the above example is one option.
Only the selected columns will be in the result.

Alternatively, it can be convenient to use `pick()` _within_ the `mutate()` call:

```{R}
starwars |> mutate(pick(c(name, species, height, mass)), BMI = mass / (height / 100)^2) |> head(4)
```

Only the `pick`ed columns are used in the mutation, but all columns are returned.

### data.table

### Polars

TODO

### DuckDB

TODO

### Arrow

TODO






[web-dataframe]: https://bioinformatics.ccr.cancer.gov/docs/rintro/Lesson_3/
[web-tibble]: https://tibble.tidyverse.org/
[ref-tibbles]: https://tibble.tidyverse.org/reference/index.html
[book-tibble]: https://r4ds.had.co.nz/tibbles.html
[ref-data-table]: https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html
[ref-tibble]: https://tibble.tidyverse.org/reference/tibble.html
[ref-tribble]: https://tibble.tidyverse.org/reference/tribble.html
[web-purrr]: https://purrr.tidyverse.org/index.html
[web-dplyr]: https://dplyr.tidyverse.org/index.html
[ref-as_tibble]: https://tibble.tidyverse.org/reference/as_tibble.html
[ref-asdataframe]: https://www.rdocumentation.org/packages/base/versions/3.1.1/topics/as.data.frame
[ref-pull]: https://dplyr.tidyverse.org/reference/pull.html
[ref-select]: https://dplyr.tidyverse.org/reference/select.html
[ref-relocate]: https://dplyr.tidyverse.org/reference/relocate.html
[ref-starts_with]: https://tidyselect.r-lib.org/reference/starts_with.html
[ref-starwars]: https://dplyr.tidyverse.org/reference/starwars.html
[ref-filter]: https://dplyr.tidyverse.org/reference/filter.html
[ref-slice]: https://dplyr.tidyverse.org/reference/slice.html
[ref-mutate]: https://dplyr.tidyverse.org/reference/mutate.html
[ref-pick]: https://dplyr.tidyverse.org/reference/pick.html
[ref-distinct]: https://dplyr.tidyverse.org/reference/distinct.html
[ref-rename]: https://dplyr.tidyverse.org/reference/rename.html
[ref-arrange]: https://dplyr.tidyverse.org/reference/arrange.html
[concept-vectors]: https://exercism.org/tracks/r/concepts/vectors
[concept-lists]: https://exercism.org/tracks/r/concepts/lists
[concept-switch]: https://exercism.org/tracks/r/concepts/switch
[concept-funcprog]: https://exercism.org/tracks/r/concepts/functional-programming
[concept-matrices-arrays]: https://exercism.org/tracks/r/concepts/matrices-arrays
[concept-functions]: https://exercism.org/tracks/r/concepts/functions
[concept-regex]: https://exercism.org/tracks/r/concepts/regular-expressions
[concept-nothingness]: https://exercism.org/tracks/r/concepts/nothingness
[wiki-bmi]: https://en.wikipedia.org/wiki/Body_mass_index
